### ISSUE TITLE
error on Compile the pictorial function for accelerate

### ISSUE THREAD

**Issue by Ariel666** [zju3dv/mvpose#10]
I follow the instructions and reach this line Compile the pictorial function for accelerate, using the command `python setup.py build_ext --inplace`, but I got this error.

(pytorch) [XXXXXX]$ python setup.py build_ext --inplace
running build_ext
skipping 'pictorial.c' Cython extension (up-to-date)
building 'pictorial' extension
gcc -pthread -B /home/ar/XXXXX/anaconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ar/XXXXXX/anaconda3/envs/pytorch/include/python3.6m -c pictorial.c -o build/temp.linux-x86_64-3.6/pictorial.o -ffast-math -O3
In file included from /usr/include/numpy/arrayobject.h:14:0,
                 from pictorial.c:593:
pictorial.c: In function ‘__pyx_pf_5numpy_7ndarray___getbuffer__’:
pictorial.c:6771:50: error: ‘NPY_ARRAY_C_CONTIGUOUS’ undeclared (first use in this function)
   __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_ARRAY_C_CONTIGUOUS) != 0)) != 0);
                                                  ^
pictorial.c:6771:50: note: each undeclared identifier is reported only once for each function it appears in
pictorial.c:6827:50: error: ‘NPY_ARRAY_F_CONTIGUOUS’ undeclared (first use in this function)
   __pyx_t_2 = ((!(PyArray_CHKFLAGS(__pyx_v_self, NPY_ARRAY_F_CONTIGUOUS) != 0)) != 0);
                                                  ^
pictorial.c: In function ‘__pyx_f_5numpy_PyDataType_SHAPE’:
pictorial.c:7786:3: warning: implicit declaration of function ‘PyDataType_HASSUBARRAY’ [-Wimplicit-function-declaration]
   __pyx_t_1 = (PyDataType_HASSUBARRAY(__pyx_v_d) != 0);
   ^
pictorial.c: In function ‘__pyx_f_5numpy_set_array_base’:
pictorial.c:8613:3: warning: implicit declaration of function ‘PyArray_SetBaseObject’ [-Wimplicit-function-declaration]
   (void)(PyArray_SetBaseObject(__pyx_v_arr, __pyx_v_base));
   ^
error: command 'gcc' failed with exit status 1

I don't know how to deal with it........

**Comment by JiangWenPL** [comment]
Hi Ariel. We have never met with this problem before. Please make sure all the dependent package has been installed, Cython, Numpy etc. Alternatively, you may try to use our unoptimized code by commenting the line #155 in `src/models/estimate3d.py` and modifying others if necessary. It might be slower and has some tiny implementation differences.

**Comment by Ariel666** [comment]
Thanks, I modified some codes in setup.py, 
`import numpy as np
include_dirs=[np.get_include()])]
`
and now it worked.....
