### ISSUE TITLE
Test a video from youtube or test my picture?

### ISSUE THREAD

**Issue by Ariel-JUAN** [zju3dv/mvpose#11]
Hi, can you please show me how to test a video from youtube or test my picture? 
If I test the picture in the wild, what camera parameters should I use?

**Comment by DongJT1996** [comment]
Hello, if you want to test your own images, you need the calibrated camera parameters of your setting, i.e. [R T] and K of each camera like the datasets Campus and Shelf.

**Comment by Ariel-JUAN** [comment]
If I test the video from youtube, how should I set the calibrated camera parameters ?

**Comment by DongJT1996** [comment]
I think you should using some algorithms to estimation the camera parameters since that is the input of our algorithm.

**Comment by lan786** [comment]
@Ariel-JUAN  Hi did you calibrate the camera?
