### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by JulesDoe** [zju3dv/mvpose#13]
I have problems compiling the backend. Which versions of QUDA and gcc did you use? Is the TF version from requirements.txt correct? thank you

**Comment by DongJT1996** [comment]
CUDA : 9.0, gcc : 5.4.0, the TF version is correct.

**Comment by JulesDoe** [comment]
And your OS? thanks

**Comment by DongJT1996** [comment]
Ubuntu 16.04
I remember that I have modified some files of tensorflow similar to the following:
```
-#include "third_party/gpus/cuda/include/cuda.h"
+#include "cuda/include/cuda.h"
```
Maybe you can have a try.

**Comment by JulesDoe** [comment]
I fowngraded to Ubuntu 16.04 and everything works fine now thank you!
