### ISSUE TITLE
What is the "s" paramter in "getK.m"? 

### ISSUE THREAD

**Issue by JulesDoe** [zju3dv/mvpose#14]
I'm trying to create my own dataset. When calibrating the camera I asked myself what the "s" parameter in the getK.m script does.

function K = getK(f,s,cx,cy,scale)

K = zeros(3,3);

K(1,1)=(f/s) * scale;
K(2,2)=(f/s) * scale;
K(1,3)=cx * scale;
K(2,3)=cy * scale;
K(3,3)=1;

**Comment by DongJT1996** [comment]
You can refer to the definition of the [intrinsic matrix](https://en.wikipedia.org/wiki/Camera_resectioning). 

![image](https://user-images.githubusercontent.com/25705996/58295422-bea40c80-7e01-11e9-932a-d58a557f72d3.png)

**Comment by JulesDoe** [comment]
Thanks a lot!
