### ISSUE TITLE
about Camera Style Training DataSet

### ISSUE THREAD

**Issue by lyokka** [zju3dv/mvpose#16]
I noticed that you trained CamStyle model by youtself.
And I also find that your code metioned this part using `Shelf` dataset.
I wonder if you use Shelf dataset as training set for Camstyle, 
and also use this reid result to generate 3D pose.
Hope this will not cause problem for other dataset with your settings.

**Comment by JiangWenPL** [comment]
We trained the CamStyle model based on the instructions from their [readme](https://github.com/zhunzhong07/CamStyle) and no information from Shelf/Campus is used for training. The only reason why we train the model by ourselves is that we have not find the pretrained model from their website.

**Comment by lyokka** [comment]
Got it, thx

**Comment by gaobaoding** [comment]
> We trained the CamStyle model based on the instructions from their [readme](https://github.com/zhunzhong07/CamStyle) and no information from Shelf/Campus is used for training. The only reason why we train the model by ourselves is that we have not find the pretrained model from their website.

Hey JiangWenPL,
I have met problem when I extract CamStyle model which trained by yourself like:

`an error occured while loading the archive`
