### ISSUE TITLE
About 3d mesh SMPL

### ISSUE THREAD

**Issue by qqcce** [zju3dv/mvpose#18]
Thank you for your work.
You visualize your joints with SMPL 3d mesh in your project page. I have no idea about how to convert 3d keypoints to SMPL format. Do you have code about mesh visualization?

**Comment by DongJT1996** [comment]
You can use different methods to fit the SMPL to the 3D skeleton.
1. You can just train a network to regress the parameters of SMPL from the 3D keypoints, which is the  way we used.
2. You can using the optimization framework to fit the SMPL to the 3D keypoints using different loss, such as the L2 distance of the 3D keypoints.

**Comment by B10532021** [comment]
May I ask how to train this network? what dataset did you used?
