### ISSUE TITLE
How to calculate the prjectionMat in camera_parameter.pickle?

### ISSUE THREAD

**Issue by dulibubai** [zju3dv/mvpose#19]
How to calculate the prjectionMat in camera_parameter.pickle?

**Comment by DongJT1996** [comment]
You can refer to the commands [here](https://github.com/zju3dv/mvpose#prepare-models-and-datasets)

**Comment by dulibubai** [comment]
Hi!  How to determine the world reference coordinates  between three or five cameras in your paper?
Or what's the world reference coordinates in the Campus and Shelf dataset?

**Comment by DongJT1996** [comment]
The Campus and Shelf datasets provide the groundtruth of 3D poses in the world reference coordinate. And the datasets also provide the Rotation matrix and Translation. So I think we don't need to determine the world reference coordinates...

**Comment by dulibubai** [comment]
Thanks!But if I want to test my own dataset? How can I determine the world reference coordinate?





------------------ 原始邮件 ------------------
发件人: "DongJT1996"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 晚上10:26
收件人: "zju3dv/mvpose"<mvpose@noreply.github.com>; 
抄送: "唯我杜尊"<1257618212@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zju3dv/mvpose] How to calculate the prjectionMat incamera_parameter.pickle? (#19)




The Campus and Shelf datasets provide the groundtruth of 3D poses in the world reference coordinate. And the datasets also provide the Rotation matrix and Translation. So I think we don't need to determine the world reference coordinates...

**Comment by DongJT1996** [comment]
To test your own dataset, you just need to know the relative R and T between each camera. With these relative Rs and Ts, you can determine the world reference coordinate arbitrarily and even set one certain camera coordinate as the world reference coordinate.

**Comment by dulibubai** [comment]
Thanks  very much!!!



------------------ 原始邮件 ------------------
发件人: "DongJT1996"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 上午9:37
收件人: "zju3dv/mvpose"<mvpose@noreply.github.com>; 
抄送: "唯我杜尊"<1257618212@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zju3dv/mvpose] How to calculate the prjectionMat incamera_parameter.pickle? (#19)




To test your own dataset, you just need to know the relative R and T between each camera. With these relative Rs and Ts, you can determine the world reference coordinate arbitrarily and even set one certain camera coordinate as the world reference coordinate.

**Comment by dulibubai** [comment]
If I only  have two cameras ,the 3d mvpose can make well?

**Comment by lan786** [comment]
@dulibubai  Did you calibrate your dataset? Which toolbox you used for multi-camera calibration?
