### ISSUE TITLE
what's the python version of you code

### ISSUE THREAD

**Issue by fanglw** [zju3dv/mvpose#20]
Hi, i meet some problems when running the code, could you tell me what's the python version, and tensorflow version for running the code.

**Comment by DongJT1996** [comment]
Hi, we use 
Python : 3.6.2
Tensorflow : 1.9.0

**Comment by dulibubai** [comment]
Hi! If we only have two cameras,the 3d mvpose can make well?

**Comment by DongJT1996** [comment]
If there are only two cameras, the SVT matching algorithm is equal to the Hungarian algorithm and the 3D pictorial structure model is equal to triangulation.

**Comment by dulibubai** [comment]
Thanks again！

**Comment by dulibubai** [comment]
So if we only have two cameras, the source code can go well,but the result is not good?

**Comment by DongJT1996** [comment]
If the result of matching and predicted 2D poses are good, I think the result should be good. But the cycle consistency constraint has no effect.

**Comment by dulibubai** [comment]
Thanks！





------------------ 原始邮件 ------------------
发件人: "DongJT1996"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 下午5:43
收件人: "zju3dv/mvpose"<mvpose@noreply.github.com>; 
抄送: "唯我杜尊"<1257618212@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zju3dv/mvpose] what's the python version of you code (#20)




If the result of matching and predicted 2D poses are good, I think the result should be good. But the cycle consistency constraint has no effect.
