### ISSUE TITLE
How to learn mean and std between two joints in the dataset(eg:Human3.6)?

### ISSUE THREAD

**Issue by dulibubai** [zju3dv/mvpose#21]

**Comment by dulibubai** [comment]
How to learn mean and std between two joints in the dataset(eg:Human3.6)?

**Comment by JiangWenPL** [comment]
Actually, we didn't try to "learn" the distribution of joints, We simply calculated the `mean` and `std` of bone length from training set. We increased the `std` by multiplying it with an arbitrary factor to add more variation as those information were obtained from a few people. There is no significant difference on performance as long as those settings are reasonable for human. If you want to test on your own data, you can calculate bone length by yourself or just try to use default parameters.
