### ISSUE TITLE
How to match detected 2D poses across views?

### ISSUE THREAD

**Issue by maoyali** [zju3dv/mvpose#22]
Thanks for your code ! I only want to match detected 2D poses across views, Can I use your code?

**Comment by JiangWenPL** [comment]
Surely, you can find the matching results [here](https://github.com/zju3dv/mvpose/blob/13afabb6133259bb042fc69a53a6c9e2025c11a7/src/models/estimate3d.py#L131), and you can modify it to meet you needs as long as you follow our [license](https://github.com/zju3dv/mvpose/blob/master/LICENSE).

**Comment by maoyali** [comment]
Thanks again！

**Comment by maoyali** [comment]
I test your code to match 2D pose across views, but the result isn't good as dataset campus, How can I get a more accurate matching? Thanks in advance~

**Comment by JiangWenPL** [comment]
Close this issue as we are discussing this problem in #23
