### ISSUE TITLE
How to test on my own data?

### ISSUE THREAD

**Issue by maoyali** [zju3dv/mvpose#23]
![image](https://user-images.githubusercontent.com/31682925/62466170-3f4c9500-b7c3-11e9-9c3e-5135e16b588e.png)
I test it on my own data,the 2D pose estimation works well , but the 3D is wrong. I think it's because my project.mat is generated wrong. Could you please tell me the meanings of these paramters. I just use each camera's parameter to the correspondence in getK.m .Thank you in advance~

**Comment by maoyali** [comment]
My camera's paramters are as follows:
![image](https://user-images.githubusercontent.com/31682925/62466800-c8b09700-b7c4-11e9-9f2b-022512dcb52d.png)
how should I set the right correapondence?

**Comment by JiangWenPL** [comment]
Hi Mao, those parameters are just in their literal meanings. For further information you could read the implementation in the [mat2pickle.py](https://github.com/zju3dv/mvpose/blob/13afabb6133259bb042fc69a53a6c9e2025c11a7/src/tools/mat2pickle.py). You can also have a look at our [dataset](https://github.com/zju3dv/mvpose/blob/13afabb6133259bb042fc69a53a6c9e2025c11a7/src/m_utils/mem_dataset.py#L61) if you have questions on how those parameters are used and transformed into fundamental matrixes.
Feel free to ask us if you have other questions.

**Comment by JulesDoe** [comment]
This might get you in the right direction.  I'm kind of shour there is still something wrong (PR if you find it ;). https://gist.github.com/JulesDoe/6b54602445d63f490709cecb4972a0f0 

my results with this look like this:
![Screenshot from 2019-08-09 19-38-37](https://user-images.githubusercontent.com/9567089/62800762-80ef7f80-bae4-11e9-9508-12289b93d868.png)

**Comment by DongJT1996** [comment]
As you can see, the geometry affinity between person 0  and others is close to zero. You maybe can plot the epipolar lines corresponding to  2D keypoints of person 0 in other views.

**Comment by JulesDoe** [comment]
Hmm maybe ther went something wrong with the calibration of this particular kamera... thanks for the tip! I will look into it.
Do i have to correct the distortion in the images bevor i pass them over?

**Comment by JiangWenPL** [comment]
We didn't un-distort the images in practice for the sake of convenience. But, theortically, it could be better if you do that.

**Comment by lan786** [comment]
@JulesDoe @JiangWenPL  Hi, I've 6GB GPU (GTX1060). All the steps and compilations was done. When I try to run the Demo, it shows CUDA out of memory. When I changed the batch size from 32 to 4 in backend/tf_cpn/Detector2D.py (line 90) then it shows following error in Detector2D.py line 220.
heatmaps = heatmaps[i], crops=crops[i]
Kindly help me in this regard that how I can solve this problem?
Thanks

**Comment by sklf** [comment]
Hello guys, I'm trying to use your code to estimate 3D poses. My dataset caontains frames from 12 cameras and camera parameters. I think my dataset is bigger than Campus and Shelf. So could you tell me what should I do to improve the performance? I just tried a little data. But the code seems very slow. Besides I can't get 3D pose plot at all. Could you help me?
