### ISSUE TITLE
cuda/include/cuda.h: No such file or directory ;  psalign_pooling_op.cu.o: No such file or directory

### ISSUE THREAD

**Issue by Yxiaoqian** [zju3dv/mvpose#24]
i have tried some methods to handle these problems, but i can't fix it, who can help me? thanks a lot!

**Comment by JiangWenPL** [comment]
Have you successfully configured the RCNN related dependencies as we described in [readme](https://github.com/zju3dv/mvpose/blob/master/README.md#installation) ?

**Comment by Yxiaoqian** [comment]
thank you! i have fixed it.

**Comment by anl13** [comment]
You should delete `-D GOOGLE_CUDA=1` in all `make.sh` under every subdirectory of `./backend/light_head_rcnn/lib/lib_kernel/`.

**Comment by gaobaoding** [comment]
change `cuda/include/cuda.h` to `cuda.h` can address your problem

**Comment by lan786** [comment]
@Yxiaoqian  Hi dear, I faced the same issue and after a little work I found solution (same as @gaobaoding ) to address this problem. Here is detail, you can follow this issue #30  to get the detail solution.
