### ISSUE TITLE
Question about live Cameras

### ISSUE THREAD

**Issue by lan786** [zju3dv/mvpose#25]
Hi, thanks for your such a nice work. I want to know that this work can be implemented for live cameras instead of images? I want to use 2 live cameras. Is it possible in your work? I read your work but still I'm confused about my problem.

**Comment by DongJT1996** [comment]
Hi, 
In theory, this method is capable of this setting. But if you have only two cameras, the occlusion may influence the result. Because if one person is only visible in one camera, it can not be recovered.

**Comment by ahsan3803** [comment]
@DongJT1996 Hi thanks for your reply, in my case I want to implement it for only one person and 2 cameras for multi-view.  So is it good regarding your repository? I read it and I came to know that your repository can be helpful for this problem.

**Comment by DongJT1996** [comment]
Yes, I think it can work in this setting.

**Comment by lan786** [comment]
Yeah sure, I'll try it. Thanks so much for your help

**Comment by sailyung** [comment]
> Yeah sure, I'll try it. Thanks so much for your help
do you try to use two cam for live? how about the result?

**Comment by Jerryzhangzhao** [comment]
@lisa676  Hi,Lisa,have you tried the code with live cameras? I am working on the 3d pose with live camera recently,  how about your result?
