### ISSUE TITLE
/mvpose/backend/light_head_rcnn/lib/lib_kernel/lib_psroi_pooling/psroi_pooling.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Vegetabbird** [zju3dv/mvpose#26]

**Comment by cbiras** [comment]
Hi, I'm facing the same issue. How did you solve it?

**Comment by ChenConnie** [comment]
Hi, I'm facing the same issue. How did you solve it？

**Comment by Vegetebird** [comment]
> Hi, I'm facing the same issue. How did you solve it？

I installed the tensorflow1.5.0 with cuda9.0 on 2080Ti (Ubuntu16), it works.

**Comment by ChenConnie** [comment]
thank you.
I'll try.
















At 2020-10-11 09:45:37, "Vegetabird" <notifications@github.com> wrote:

Hi, I'm facing the same issue. How did you solve it？

I installed the tensorflow1.5.0 with cuda9.0 on 2080Ti (Ubuntu16), it works.
