### ISSUE TITLE
Tensorflow: Cannot open shared object file

### ISSUE THREAD

**Issue by lan786** [zju3dv/mvpose#30]
@DongJT1996 Hi, when I try to run the demo 
`python ./src/m_utils/demo.py -d Campus`
`python ./src/m_utils/demo.py -d Shelf`
It shows this error
`tensorflow.python.framework.errors_impl.NotFoundError: ${mvpose_root}/backend/light_head_rcnn/lib/lib_kernal/lib_psroi_pooling.so: cannot open shared object file: No such file or directory`.

System environment is 
Ubuntu 16.04
CUDA: 9.0
CuDNN: 7
Python 3.6.9 (Anaconda)
Tensorflow-GPU 1.9

Everything is working fine (tf, pytorch etc.) and compilation was also successful but at the time of running demo I got above mentioned error. Can you help me that what is this problem and how we can solve it?

**Comment by lan786** [comment]
I solved the problem. This problem was due to missing or incorrect path of `cuda.h` and `cuda_fp16.h` file.
Here I'll explain in detail because others are also facing this problem as I read other issues in this repository. 

The above mentioned problem is occur when to compile `light_head_rcnn/lib/make.sh`, it compile following 7 repositories. 
[https://github.com/zju3dv/mvpose/blob/master/backend/light_head_rcnn/lib/make.sh](url)
`1: ./utils/py_faster_rcnn_utils` 
`2: lib_kernel/lib_psroi_pooling`
`3: lib_kernel/lib_roi_pooling`
`4: lib_kernel/lib_roi_alig`
`5: lib_kernel/lib_psalign_pooling`
`6: lib_kernel/lib_nms_dev`
`7: datasets_odgt/lib_coco/PythonAPI`
and the compilation error is only in 2 and 5 because `cuda_kernal_helper.h, cuda_devices_functions.h and cunda_lunch_config.h` in tensorflow use `cuda.h` and `cuda_fp16.h` files from CUDA for compilation.

**Solution**
1: Copy `cuda.h` and `cuda_fp16.h` file from `/usr/local/cuda/include` to (as in my case or for example) `/anaconda3/envs/test/lib/python3.6/site-packges/tensorflow/include/tensorflow/core/util/` .
Check your python environment directory for tensorflow to paste the above mentioned file.

2: Open `cuda_kernal_helper.h, cuda_devices_functions.h and cunda_lunch_config.h` files in `/anaconda3/envs/test/lib/python3.6/site-packges/tensorflow/include/tensorflow/core/util/` and edit path for `cuda.h` and `cuda_fp16.h` in line 24, 32 and 24 respectively. Line numbers can be changed in different versions of CUDA.

3: Compile again 2 and 5, hope so there will be no problem if other environment is accurate as for this repository.

**Comment by wangziyi2016** [comment]
> I solved the problem. This problem was due to missing or incorrect path of `cuda.h` and `cuda_fp16.h` file.
> Here I'll explain in detail because others are also facing this problem as I read other issues in this repository.
> 
> The above mentioned problem is occur when to compile `light_head_rcnn/lib/make.sh`, it compile following 7 repositories.
> [https://github.com/zju3dv/mvpose/blob/master/backend/light_head_rcnn/lib/make.sh](url)
> `1: ./utils/py_faster_rcnn_utils`
> `2: lib_kernel/lib_psroi_pooling`
> `3: lib_kernel/lib_roi_pooling`
> `4: lib_kernel/lib_roi_alig`
> `5: lib_kernel/lib_psalign_pooling`
> `6: lib_kernel/lib_nms_dev`
> `7: datasets_odgt/lib_coco/PythonAPI`
> and the compilation error is only in 2 and 5 because `cuda_kernal_helper.h, cuda_devices_functions.h and cunda_lunch_config.h` in tensorflow use `cuda.h` and `cuda_fp16.h` files from CUDA for compilation.
> 
> **Solution**
> 1: Copy `cuda.h` and `cuda_fp16.h` file from `/usr/local/cuda/include` to (as in my case or for example) `/anaconda3/envs/test/lib/python3.6/site-packges/tensorflow/include/tensorflow/core/util/` .
> Check your python environment directory for tensorflow to paste the above mentioned file.
> 
> 2: Open `cuda_kernal_helper.h, cuda_devices_functions.h and cunda_lunch_config.h` files in `/anaconda3/envs/test/lib/python3.6/site-packges/tensorflow/include/tensorflow/core/util/` and edit path for `cuda.h` and `cuda_fp16.h` in line 24, 32 and 24 respectively. Line numbers can be changed in different versions of CUDA.
> 
> 3: Compile again 2 and 5, hope so there will be no problem if other environment is accurate as for this repository.

Thanks a lot for sharing your solution, it works for me!

**Comment by khanhha** [comment]
> I solved the problem. This problem was due to missing or incorrect path of `cuda.h` and `cuda_fp16.h` file.
> Here I'll explain in detail because others are also facing this problem as I read other issues in this repository.
> 
> The above mentioned problem is occur when to compile `light_head_rcnn/lib/make.sh`, it compile following 7 repositories.
> [https://github.com/zju3dv/mvpose/blob/master/backend/light_head_rcnn/lib/make.sh](url)
> `1: ./utils/py_faster_rcnn_utils`
> `2: lib_kernel/lib_psroi_pooling`
> `3: lib_kernel/lib_roi_pooling`
> `4: lib_kernel/lib_roi_alig`
> `5: lib_kernel/lib_psalign_pooling`
> `6: lib_kernel/lib_nms_dev`
> `7: datasets_odgt/lib_coco/PythonAPI`
> and the compilation error is only in 2 and 5 because `cuda_kernal_helper.h, cuda_devices_functions.h and cunda_lunch_config.h` in tensorflow use `cuda.h` and `cuda_fp16.h` files from CUDA for compilation.
> 
> **Solution**
> 1: Copy `cuda.h` and `cuda_fp16.h` file from `/usr/local/cuda/include` to (as in my case or for example) `/anaconda3/envs/test/lib/python3.6/site-packges/tensorflow/include/tensorflow/core/util/` .
> Check your python environment directory for tensorflow to paste the above mentioned file.
> 
> 2: Open `cuda_kernal_helper.h, cuda_devices_functions.h and cunda_lunch_config.h` files in `/anaconda3/envs/test/lib/python3.6/site-packges/tensorflow/include/tensorflow/core/util/` and edit path for `cuda.h` and `cuda_fp16.h` in line 24, 32 and 24 respectively. Line numbers can be changed in different versions of CUDA.
> 
> 3: Compile again 2 and 5, hope so there will be no problem if other environment is accurate as for this repository.

that solutions works for me. Thanks

**Comment by ChenConnie** [comment]
Thank you. It works for me

**Comment by yumworm** [comment]
Works for me but I had to downgrade my Tensorflow from 1.14 to 1.9 first because 1.14 will give you error for not having cuda_kernel_helper.h

psalign_pooling_op_gpu.cu.cc:7:53: fatal error: tensorflow/core/util/cuda_kernel_helper.h: No such file or directory
 #include "tensorflow/core/util/cuda_kernel_helper.h

And then for tf 1.9 I had to use conda install instead of pip install because it didn't find the version 1.9

~/pose3d/mvpose$ pip install tensorflow-gpu==1.9.0
Collecting tensorflow-gpu==1.9.0
  ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.9.0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow-gpu==1.9.0

~/pose3d/mvpose$ conda install tensorflow-gpu==1.9.0

And bash make.sh works!
