### ISSUE TITLE
List index out of range and CUDA out of Memory

### ISSUE THREAD

**Issue by lan786** [zju3dv/mvpose#31]
@DongJT1996  Hi, I've 6GB GPU (GTX1060). All the steps and compilations was done. When I try to run the Demo, it shows CUDA out of memory. When I changed the batch size from 32 to 4 in `backend/tf_cpn/Detector2D.py` (line 90) then it shows following error in Detector2D.py line 220.
`heatmaps = heatmaps[i], crops=crops[i]` 
Kindly help me in this regard that how I can solve this problem?
Thanks

**Comment by DongJT1996** [comment]
Hi~
I think the reason is the 2D pose estimator CPN requires much memory, but a 1080Ti is enough. You maybe go to [their repo](https://github.com/chenyilun95/tf-cpn) and see whether they can reduce the requirement of memory.
