### ISSUE TITLE
How much GPU memory is required for running the demo of Campus?

### ISSUE THREAD

**Issue by gaobaoding** [zju3dv/mvpose#32]
Hi guys, 
My GPU is GTX970m and the available memory is ~2.95 GB.
Do you know how much GPU memory is necessary for running the demo of Campus like :
`python ./src/m_utils/demo.py -d Campus`

it seems that my GPU memory is not enough :(

**Comment by lan786** [comment]
In my case my GPU memory is 6GB and I'm unable to run it. As author said in previous issue that GTX1080ti is enough. 
Duplicate of #31

**Comment by gaobaoding** [comment]
Hi @lan786,
thanks for your information. Wow, that memory is more than I thought.

**Comment by gaobaoding** [comment]
@lan786 
btw, can you run the demo command that I mentioned above with your GPU?

**Comment by lan786** [comment]
@gaobaoding  Hi, I already test it but facing memory issue. I mentioned it in issue 31. [https://github.com/zju3dv/mvpose/issues/31](url)
