### ISSUE TITLE
_pickle.UnpicklingError: unpickling stack underflow

### ISSUE THREAD

**Issue by Felix1014** [zju3dv/mvpose#33]
when run python ./src/m_utils/demo.py -d Campus， I got the error_pickle.UnpicklingError: unpickling stack underflow. How can I solve this? I have no ideas. Thank you.

**Comment by DongJT1996** [comment]
Have you downloaded the corresponding [pickle file](https://github.com/zju3dv/mvpose#prepare-models-and-datasets)?
