### ISSUE TITLE
Bad visual results

### ISSUE THREAD

**Issue by anl13** [zju3dv/mvpose#34]
I run your code without modification of the parameters or rendering, and get reprojection image like this 
(2212th frame of Shelf) 
![002212](https://user-images.githubusercontent.com/10414372/69035015-8a5e8100-0a1d-11ea-915c-85427d5d754e.png)
(2313th frame of Shelf)
![002313](https://user-images.githubusercontent.com/10414372/69035133-dc070b80-0a1d-11ea-8fc3-b851b22ace40.png)

Such artifacts are frequently seen in your results. But your video (in smpl model) seems very well without any false positive human instances or false pose. Why? Should I change some parameters? 

By the way, parameters I use is 
```
joint_num = 17
rerank = False
use_mincut = False
metric = 'geometry mean'
testing_on = 'Shelf'
reprojection_refine = False
refine_threshold = 1
semantic_matching = False
match_SVT = True
dual_stochastic_SVT = False
lambda_SVT = 50
alpha_SVT = 0.5
eta = 1.5
beta = 0.5
use_bundle = False
spectral = True
hybrid = True
```

**Comment by lyshuga** [comment]
+1

**Comment by DongJT1996** [comment]
Our code generates the single-frame result. When the input is a video, we are able to adopt a simple tracking algorithm to smooth the motion and remove the false positive results.

**Comment by lyshuga** [comment]
> Our code generates the single-frame result. When the input is a video, we are able to adopt a simple tracking algorithm to smooth the motion and remove the false positive results.

Could you, please, share the code for tracking through video frames?

**Comment by DongJT1996** [comment]
We did not organize the code of tracking, which is not our contribution. You may use any simple tracking algorithm to realize it.
