### ISSUE TITLE
Campus dataset image files corrupted(?)

### ISSUE THREAD

**Issue by rrbarioni** [zju3dv/mvpose#40]
Hello,

I have downloaded the Campus dataset [here](http://campar.cs.tum.edu/files/belagian/multihuman/CampusSeq1.tar.bz2) (I got the link from the readme), but all the frames from the three cameras are corrupted. Is there another link for downloading the dataset?

**Comment by DongJT1996** [comment]
Hi,
I have tried to download again and find it's ok for me. I think it may due to poor network.
