### ISSUE TITLE
Generate the camera parameters:FileNotFoundError: [Errno 2] No such file or directory: './datasets/CampusSeq1/Calibration/intrinsic.mat'

### ISSUE THREAD

**Issue by ssw2002com** [zju3dv/mvpose#45]
Do we have code to calibrate camera?  
How to get intrinsic mat and extrinsic mat?

python src/tools/mat2pickle.py ./datasets/CampusSeq1/Calibration/ ./datasets/CampusSeq1

FileNotFoundError: [Errno 2] No such file or directory: './datasets/CampusSeq1/Calibration/intrinsic.mat'

**Comment by ssw2002com** [comment]
How to get the intrinsic.mat?
I have tried to do these following steps, but I failed. Because I don't have some files,such as intrinsic.mat,m_RT.mat.

My command is "python ./src/tools/mat2pickle.py ./datasets/CampusSeq1/Calibration/ ./datasets/CampusSeq1"

Thanks!
    Add following code to .datasets/CampusSeq1/Calibration/producePmat.m

K = cell(1,3);
K{1} = K1; K{2} = K2; K{3} = K3;
m_RT = cell(1,3);
m_RT{1} = RT1; m_RT{2} = RT2; m_RT{3} = RT3;
save('intrinsic.mat','K');
save('m_RT.mat', 'm_RT');
save('P.mat', 'P');
save('prjectionMat','P');

    generate the camera_parameter.pickle

python ./src/tools/mat2pickle.py /parameter/dir ./datasets/CampusSeq1

**Comment by DongJT1996** [comment]
Hi, Do you run the producePmat.m file?

**Comment by ssw2002com** [comment]
Well, thank you, I will try it at once.

**Comment by Taylorminer** [comment]
@DongJT1996  I meet the same problem. "Do you run the producePmat.m file ?"What is that mean ?.
