### ISSUE TITLE
Docker for mvpose

### ISSUE THREAD

**Issue by siehlema** [zju3dv/mvpose#49]
Hello,

I would like to propose to add a docker image for the use of this framework. It would make it much easier to start working with it.

I am currently working on a running docker solution based on the nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 container. If I succeed in creating one I could also add it to this repo if you are interested.

Cheers,
Martin

**Comment by hytu99** [comment]
hello, have you succeed?

**Comment by siehlema** [comment]
I created my own repo with a Dockerfile and a entrypoint. This works for me.

Repo:
https://github.com/siehlema/hpe-testing_in_the_wild-mvpose
