### ISSUE TITLE
what does the camera parameters mean?

### ISSUE THREAD

**Issue by park-youngsin** [zju3dv/mvpose#58]
i dont know to mean such as focal, kappa, cx, cy, sx, tx, ty, tz, rx, ry, rz.
I got the following camera parameter

### Intrinsics: 
Camera #1 :
....Focal length: [519.5165, 522.6614]
....Aspect ratio: 0
....Principle Point: [311.6374, 248.4914]
....Distortion Coeff: [0.074177, -0.19382, 0.004672, -0.0024758]
Camera #2 :
....Focal length: [533.2476, 534.1122]
....Aspect ratio: 0
....Principle Point: [323.0905, 238.1405]
....Distortion Coeff: [-0.015774, -0.12482, 0.0092172, -1.2588e-05]
Camera #3 :
....Focal length: [696.9331, 702.9498]
....Aspect ratio: 0
....Principle Point: [346.0417, 252.4627]
....Distortion Coeff: [-0.047315, -0.19989, 0.0037186, -0.0093026]
### Extrinsics: 
Extrinsics: 
Camera #1 :
1  0  0  0
0  1  0  0
0  0  1  0
0  0  0  1
Camera #2 :
   0.9964741    0.00668053    0.08363466     -713.6928
-0.007989875     0.9998506    0.01533062     -4.340179
 -0.08351974    -0.0159448     0.9963786      43.18932
           0             0             0             1
Camera #3 :
   0.97432572    0.014962601     0.22464528     -1555.7875
-0.0088870253     0.99956752   -0.028032073      5.1487088
  -0.22496756    0.025315941     0.97403732      456.78079
            0              0              0              1

How do I get it?

I used this toolbox.(https://github.com/prclibo/calibration-toolbox)

**Comment by lan786** [comment]
@park-youngsin  Did you try your data with MVPose?

**Comment by ahsan3803** [comment]
@park-youngsin  You need to assign your own camera parameters to MVPose that means camera-world coordinate system if you want to test your own data. I suggest you that you should study more about camera parameters. Below is very simple idea

![WeChat Image_20200617121848](https://user-images.githubusercontent.com/58796370/84854930-6dfaf380-b095-11ea-8ebd-c06f600b86f0.jpg)

**Comment by park-youngsin** [comment]
> @park-youngsin You need to assign your own camera parameters to MVPose that means camera-world coordinate system if you want to test your own data. I suggest you that you should study more about camera parameters. Below is very simple idea
> 
> ![WeChat Image_20200617121848](https://user-images.githubusercontent.com/58796370/84854930-6dfaf380-b095-11ea-8ebd-c06f600b86f0.jpg)
> 
> By following above screenshot you can find all these parameters from your results. For example from your result - Intrinsic parameter in camera one:
> Focal length: [519.5165, 522.6614] here 519.5165 is fx and 522.6614 is fy.

I studied about camera parameters. i know 'cx, cy = 311.6374, 248.4914' but the following is not in the calibration result.
- there is no fx,fy in focal
- kappa is not exist
- sx is not exist

i think fx≒fy=focal. and I have no idea what sx, kappa means.

**Comment by park-youngsin** [comment]
> @park-youngsin Did you try your data with MVPose?

yes, I tried using my own data for mvpose.

**Comment by lan786** [comment]
> > @park-youngsin Did you try your data with MVPose?
> 
> yes, I tried using my own data for mvpose.

So what about results?

**Comment by park-youngsin** [comment]
> > > @park-youngsin Did you try your data with MVPose?
> > 
> > 
> > yes, I tried using my own data for mvpose.
> 
> So what about results?

no 3d plot in my own data. but It is drawn by modifying the 'length' and 'error_cnt' variables in the check_bone_length function of src/m_utils/geometry.py.

**Comment by ahsan3803** [comment]
> > @park-youngsin You need to assign your own camera parameters to MVPose that means camera-world coordinate system if you want to test your own data. I suggest you that you should study more about camera parameters. Below is very simple idea
> > ![WeChat Image_20200617121848](https://user-images.githubusercontent.com/58796370/84854930-6dfaf380-b095-11ea-8ebd-c06f600b86f0.jpg)
> > By following above screenshot you can find all these parameters from your results. For example from your result - Intrinsic parameter in camera one:
> > Focal length: [519.5165, 522.6614] here 519.5165 is fx and 522.6614 is fy.
> 
> I studied about camera parameters. i know 'cx, cy = 311.6374, 248.4914' but the following is not in the calibration result.
> 
> * there is no fx,fy in focal
> * kappa is not exist
> * sx is not exist
> 
> i think fx≒fy=focal. and I have no idea what sx, kappa means.

@park-youngsin no need of kappa or sx. share your WeChat ID or email then I will share you modified files to get required parameters.

**Comment by park-youngsin** [comment]
> > > @park-youngsin You need to assign your own camera parameters to MVPose that means camera-world coordinate system if you want to test your own data. I suggest you that you should study more about camera parameters. Below is very simple idea
> > > ![WeChat Image_20200617121848](https://user-images.githubusercontent.com/58796370/84854930-6dfaf380-b095-11ea-8ebd-c06f600b86f0.jpg)
> > > By following above screenshot you can find all these parameters from your results. For example from your result - Intrinsic parameter in camera one:
> > > Focal length: [519.5165, 522.6614] here 519.5165 is fx and 522.6614 is fy.
> > 
> > 
> > I studied about camera parameters. i know 'cx, cy = 311.6374, 248.4914' but the following is not in the calibration result.
> > 
> > * there is no fx,fy in focal
> > * kappa is not exist
> > * sx is not exist
> > 
> > i think fx≒fy=focal. and I have no idea what sx, kappa means.
> 
> @park-youngsin no need of kappa or sx. share your WeChat ID or email then I will share you modified files to get required parameters.

oh thank you. 
email : dudtls531@gmail.com

**Comment by lan786** [comment]
> > > > @park-youngsin Did you try your data with MVPose?
> > > 
> > > 
> > > yes, I tried using my own data for mvpose.
> > 
> > 
> > So what about results?
> 
> no 3d plot in my own data. but It is drawn by modifying the 'length' and 'error_cnt' variables in the check_bone_length function of src/m_utils/geometry.py.

Can you elaborate more about it that how much value you entered for length and error_cnt?

**Comment by park-youngsin** [comment]
> > > > > @park-youngsin Did you try your data with MVPose?
> > > > 
> > > > 
> > > > yes, I tried using my own data for mvpose.
> > > 
> > > 
> > > So what about results?
> > 
> > 
> > no 3d plot in my own data. but It is drawn by modifying the 'length' and 'error_cnt' variables in the check_bone_length function of src/m_utils/geometry.py.
> 
> Can you elaborate more about it that how much value you entered for length and error_cnt?

i just entered all 10000.

**Comment by lan786** [comment]
> > > > > > @park-youngsin Did you try your data with MVPose?
> > > > > 
> > > > > 
> > > > > yes, I tried using my own data for mvpose.
> > > > 
> > > > 
> > > > So what about results?
> > > 
> > > 
> > > no 3d plot in my own data. but It is drawn by modifying the 'length' and 'error_cnt' variables in the check_bone_length function of src/m_utils/geometry.py.
> > 
> > 
> > Can you elaborate more about it that how much value you entered for length and error_cnt?
> 
> i just entered all 10000.
> The variable was modified because the data in pose_3d was empty.
> 
> I used this calibration toolbox (https://github.com/prclibo/calibration-toolbox) and I'm not sure it's working properly.
> 
> Do you have any calibration toolbox I can recommend?

I don't know about any method, I'm reading about this repository.

**Comment by park-youngsin** [comment]
> > > > > > > @park-youngsin Did you try your data with MVPose?
> > > > > > 
> > > > > > 
> > > > > > yes, I tried using my own data for mvpose.
> > > > > 
> > > > > 
> > > > > So what about results?
> > > > 
> > > > 
> > > > no 3d plot in my own data. but It is drawn by modifying the 'length' and 'error_cnt' variables in the check_bone_length function of src/m_utils/geometry.py.
> > > 
> > > 
> > > Can you elaborate more about it that how much value you entered for length and error_cnt?
> > 
> > 
> > i just entered all 10000.
> > The variable was modified because the data in pose_3d was empty.
> > I used this calibration toolbox (https://github.com/prclibo/calibration-toolbox) and I'm not sure it's working properly.
> > Do you have any calibration toolbox I can recommend?
> 
> I don't know about any method, I'm reading about this repository.

okey, thanks for your answer
