### ISSUE TITLE
What camera calibration toolbox did you use?

### ISSUE THREAD

**Issue by PriyaThakur** [zju3dv/mvpose#59]
Hi, Thanks for such amazing work. I wanted to know what camera calibration toolbox did you use to get the camera parameters? If it's not publicly available could you help by explaining the parameters present in camera_parameter.pickle.

**Comment by DongJT1996** [comment]
Hi,
The camera parameters are provided by the original dataset (Campus and Shelf) and we do not calibrate the cameras.
