### ISSUE TITLE
missing file reid/utils/data.py

### ISSUE THREAD

**Issue by bmauchly** [zju3dv/mvpose#6]
demo.py calls mem_dataset and can't find a file that has some torchvision transforms in it:

File "/root/mvpose/src/m_utils/mem_dataset.py", line 13, in <module>
    from backend.CamStyle.reid.utils.data import transforms as T

(thanks in advance!)

full error message:

Traceback (most recent call last):
  File "./src/m_utils/demo.py", line 20, in <module>
    from src.models.estimate3d import MultiEstimator
  File "/root/mvpose/src/models/estimate3d.py", line 25, in <module>
    from src.m_utils.mem_dataset import MemDataset
  File "/root/mvpose/src/m_utils/mem_dataset.py", line 13, in <module>
    from backend.CamStyle.reid.utils.data import transforms as T
ModuleNotFoundError: No module named 'backend.CamStyle.reid.utils.data'

**Comment by bmauchly** [comment]
The whole problem was more -  the reid utilities were out-of-date in other ways.  
I fixed it by grabbing code from another project, open-reid.


git clone (open-reid)
rm -r /root/mvpose/backend/CamStyle/reid/utils
cp -r /root/open-reid/reid/utils /root/mvpose/backend/CamStyle/reid/utils

**Comment by bmauchly** [comment]
but yeah, it could be fixed :-)

**Comment by JiangWenPL** [comment]
Well, it might be the issue of our `.gitignore` file which ignores that directory. You can refer to original [CamStyle](https://github.com/zhunzhong07/CamStyle) for those files and we will upload those files as soon as possible.

**Comment by JiangWenPL** [comment]
OK, I have uploaded those files. Thank you for your report. @bmauchly
