### ISSUE TITLE
How to use the camera-calibration file called pickle?

### ISSUE THREAD

**Issue by ssw2002com** [zju3dv/mvpose#60]
Hello, when I unpack camera-calibration file called pickle files, I found it contain three RT matrices.
if there are  three cameras, one is set as main camera, and others are estimated for extrinsic parameters by that main camera.
So, there should have two RT matrices in pickle file.
That confuse me much, can you tell me why?  Thanks.

read camera_parameter of compus:

{'K': array([[[437.98523,   0.     , 185.3596 ],
        [  0.     , 437.98523, 139.2537 ],
        [  0.     ,   0.     ,   1.     ]],

       [[430.03326,   0.     , 184.0583 ],
        [  0.     , 430.03326, 130.7467 ],
        [  0.     ,   0.     ,   1.     ]],

       [[700.98566,   0.     , 167.59476],
        [  0.     , 700.98566, 142.0545 ],
        [  0.     ,   0.     ,   1.     ]]], dtype=float32), 

'P': array([[[ 4.39056672e+02,  1.80810350e+02, -2.69460299e+01,
          1.85946083e+02],
        [-5.34160438e+00,  8.85231938e+01, -4.50952054e+02,
          1.32401438e+03],
        [ 6.05943392e-03,  9.93479680e-01, -1.13848185e-01,
          5.22697300e+00]],

       [[ 1.62357367e+02, -4.38337316e+02, -1.75084553e+01,
          3.34740830e+03],
        [ 7.33002050e+01, -1.00425050e+01, -4.43339072e+02,
          1.37348205e+03],
        [ 9.90345298e-01, -4.78873156e-02, -1.30088417e-01,
          6.68494200e+00]],

       [[ 2.37583262e+02,  6.79931118e+02, -2.67722433e+01,
         -1.55826240e+03],
        [-4.31136283e+01,  2.19818082e+01, -7.13595390e+02,
          1.96278700e+03],
        [-8.35570003e-01,  5.33251072e-01, -1.32159237e-01,
          1.12023900e+01]]]),

 'RT': array([[[ 9.9988192e-01, -7.6273032e-03, -1.3341035e-02, -1.7875570e+00],
        [-1.4122401e-02, -1.1375390e-01, -9.9340856e-01,  1.3610940e+00],
        [ 6.0594338e-03,  9.9347967e-01, -1.1384819e-01,  5.2269731e+00]],

       [[-4.6331078e-02, -9.9881405e-01,  1.4964883e-02,  4.9228501e+00],
        [-1.3065076e-01, -8.7932656e-03, -9.9138945e-01,  1.1614170e+00],
        [ 9.9034530e-01, -4.7887314e-02, -1.3008842e-01,  6.6849418e+00]],

       [[ 5.3869921e-01,  8.4247237e-01, -6.5950691e-03, -4.9012761e+00],
        [ 1.0782368e-01, -7.6704718e-02, -9.9120659e-01,  5.2987832e-01],
        [-8.3556998e-01,  5.3325105e-01, -1.3215923e-01,  1.1202390e+01]]],
      dtype=float32)}

**Comment by DongJT1996** [comment]
Hi,
Here we just extract the camera parameters from original .mat files provided by previous work (Campus and Shelf dataset). I think they may set another world coordinate and all cameras are relative to the world coordinate.
