### ISSUE TITLE
What is the expected running time of 3D estimation for 1 frame?

### ISSUE THREAD

**Issue by tjumiao** [zju3dv/mvpose#62]
Hi, 

I have run your code on the Shelf dataset with an RTX 2080Ti GPU. It takes me about 7-8 seconds to generate the 3D estimation for each frame.  However, as I see in your paper, you said you only take about 100 ms with a GTX 1080Ti GPU. Could you please give me some possible reasons why it takes so much time for me?

Thank you very much.

![image](https://user-images.githubusercontent.com/18041918/92314319-0cffff00-efa4-11ea-9d1f-52dda6c8c7d9.png)

**Comment by qhdqhd** [comment]
so why?

**Comment by yujun0-0** [comment]
Hi,

Have you solved the problem about running time? 
I meet the same problem. Could you help me? Thanks a lot!
