### ISSUE TITLE
Test with Human3.6M

### ISSUE THREAD

**Issue by mobiusww** [zju3dv/mvpose#68]
Hi, 

I am just wondering if anyone has ever tried the model using the Human3.6M dataset. I gave it a go using the Human3.6M's data and intrinsic/extrinsic parameters, but the results were not good. It sometimes reconstructed the 3D subject from two cameras but not from the other two (Figure 1~3 below). And sometimes it just assumed there were 4 persons from 4 cameras and thus no 3D reconstruction at all (Figure 4, 5 below).

I guess it was because the intrinsic/extrinsic parameters were not properly set? But it seems the projected 3D model aligns well with the unrecognized image (e.g. the 1st and 3rd images on the last row of Figure 2 below), which means that the intrinsic/extrinsic parameters were correct? Any suggestion to improve the result is much appreciated! Thanks!

Figure 1
![Figure_1](https://user-images.githubusercontent.com/47728723/94686684-8229de80-036e-11eb-9675-07e221aa4831.png)
Figure 2
![Figure_2](https://user-images.githubusercontent.com/47728723/94686689-83f3a200-036e-11eb-9864-bdd92d401e45.png)
Figure 3
![Figure_3](https://user-images.githubusercontent.com/47728723/94686696-85bd6580-036e-11eb-91f6-f058134ad996.png)

Figure 4
![Figure_4](https://user-images.githubusercontent.com/47728723/94687404-8f939880-036f-11eb-8371-b941b5456516.png)
Figure 5
![Figure_5](https://user-images.githubusercontent.com/47728723/94687411-91f5f280-036f-11eb-8c69-3f019bc19564.png)

**Comment by DongJT1996** [comment]
Hi,
Since the geometric affinity matrix is computed using normalized values, it will have some problems if there is only one person. It can be solved by using no normalization or  [adding some noise](https://github.com/zju3dv/mvpose/blob/d220e2421e5a24a3352feac61a298c2361eeeb7d/src/m_utils/geometry.py#L89-L91). You can have a try.

**Comment by mobiusww** [comment]
@DongJT1996 
I see. Much appreciated!
