### ISSUE TITLE
关于参数dual_stochastic

### ISSUE THREAD

**Issue by JordenQiao** [zju3dv/mvpose#77]
我在阅读matchSVT函数部分代码时，没办法理解dual_stochastic部分的作用，即‘Projection for double stochastic constraint’，该怎么理解这个“对偶猜测？”比较好一些。
非常感谢！

**Comment by DongJT1996** [comment]
你好，关于double stochastic constraint，核心就是想让矩阵的行和列最多只有一个1，在数值优化里就近似为行和与列和小于等于1

**Comment by JordenQiao** [comment]
还有关于您最新发的motion capture from internet videos的复现问题，想请教您一下相似性矩阵的计算是否是sigmoid(1/欧几里得距离）？以及后续的ADMM迭代优化中是否需要double stochastic constraint，我自己计算出的相似性矩阵中1占了绝大多数，以至于使用动态时间规整算法都毫无意义，想咨询您一些实现的具体细节，非常感谢！

**Comment by DongJT1996** [comment]
1. 使用了sigmoid函数，把affinity的值warp到0到1，如果绝大部分值是1的话肯定是不行的，你warp一下应该就行了
2. 我们实验发现，ADMM算法里是否使用double stochastic constraint在绝大部分情况下，影响不大
