### ISSUE TITLE
Not same results as paper showed

### ISSUE THREAD

**Issue by uljnz** [zju3dv/mvpose#8]
Hello, my test is on Campus and the parameter as below set:
    
    joint_num = 17
    rerank = True
    metric = 'circle'
    testing_on = 'Campus'
    reprojection_refine = False 
    refine_threshold = 1
    semantic_matching = False
    match_SVT = True
    dual_stochastic_SVT = False
    lambda_SVT = 50
    alpha_SVT = 0.5
    eta = 1.5
    beta = 0.5
    # if use top_down method:
    use_bundle = False
    use_mincut = False
    # else use hybrid method:
    spectral = True
    hybrid = True

my results are:

Bone Group | Actor 0 | Actor 1 | Actor 2 | Average
-- | -- | -- | -- | --
Head | 0.9592 | 0.9365 | 0.9348 | 0.9435
Torso | 0.9592 | 0.9577 | 0.942 | 0.953
Upper arms | 0.9388 | 0.9577 | 0.9275 | 0.9413
Lower arms | 0.8673 | 0.6508 | 0.8333 | 0.7838
Upper legs | 0.9592 | 0.9577 | 0.9167 | 0.9445
Lower legs | 0.9592 | 0.9577 | 0.9239 | 0.9469
Total | **0.9367 | 0.8942 | 0.908 | 0.913**
testing_on: Campusalpha:0.5lambda:50 |   |   |   |  

It's not as your paper showed (Campus data): 
![Screenshot from 2019-05-07 10-35-15](https://user-images.githubusercontent.com/44756398/57285599-d9614c00-70b3-11e9-971d-92616210dbe8.png)

what I am ignored? or where is not correct? THK a lot. :)

**Comment by DongJT1996** [comment]
Hello, I find that you have changed the default parameters. Our default parameters are shown below:

>     
    joint_num = 17
    rerank = False
    use_mincut = False
    metric = 'geometry mean'
    testing_on = 'Shelf'
    reprojection_refine = False
    refine_threshold = 1
    semantic_matching = False
    match_SVT = True
    dual_stochastic_SVT = False
    lambda_SVT = 50
    alpha_SVT = 0.5
    eta = 1.5
    beta = 0.5
    use_bundle = False
    spectral = True
    hybrid = True
And using these default parameters, you can get the following result on Campus:
![image](https://user-images.githubusercontent.com/25705996/57306785-03e3f100-7116-11e9-8d0d-4c76abf6a5ae.png)

**Comment by uljnz** [comment]
Yes, I have changed the parameter. Because when I using the default parameters have the error: 'cannot get any pose in image' and got the very bad results on Campus:
![Screenshot from 2019-05-08 10-36-35](https://user-images.githubusercontent.com/44756398/57362745-bd2ae100-717f-11e9-8caf-2691f44c627a.png)

![Screenshot from 2019-05-08 10-52-07](https://user-images.githubusercontent.com/44756398/57362658-98366e00-717f-11e9-982e-7df825358570.png)

**Comment by uljnz** [comment]
Yes, you are right. I got the best results as your paper showed when I using the default parameter. Because I made a mistake in my code, sorry for that. Thanks a lot for your help :)

**Comment by cbiras** [comment]
Hi @DongJT1996 . Could the Cuda Out of memory error cause the "ERROR Cannot get any pose in img"?
