### ISSUE TITLE
Difference between version CVPR2019 and TPAMI2021?

### ISSUE THREAD

**Issue by superobk** [zju3dv/mvpose#94]
May I know what is the difference between version CVPR2019 and TPAMI2021? For the code implementation, are the same in mvpose? Thank you in advance.

**Comment by raypine** [comment]
The pami version of mvpose additionally supports appearance feature selection, tracking and filtering.

**Comment by superobk** [comment]
> The pami version of mvpose additionally supports appearance feature selection, tracking and filtering.

Thanks for the update. 
May I know how to get the demo codes (pami version) for the evaluation? 
We are doing similar research on the tracking and filtering.
Thank you!

**Comment by raypine** [comment]
It is recommended to use [EasyMocap](https://github.com/zju3dv/EasyMocap/blob/b2d5bbcfd75a705e49eb3a6800be2d8b2e758bae/doc/mvmp.md#2-recovering-smpl-body-model) for more convenient usage.

**Comment by superobk** [comment]
Thanks!
